SECRET_KEY="demo"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "lax"


HOSTNAME = "45.207.196.148"
PORT = "3306"
DATABASE = "adventurex"
USERNAME = "adventureX"
PASSWORD = "adventureX"
DB_URI = "mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8mb4".format(USERNAME,PASSWORD,HOSTNAME,PORT,DATABASE)
SQLALCHEMY_DATABASE_URI  = DB_URI