"""empty message

Revision ID: 1488a6d6dc5a
Revises: 5d1a57c20330
Create Date: 2025-07-25 10:10:34.917114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1488a6d6dc5a'
down_revision = '5d1a57c20330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('behavior_weights', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('behavior_weights')
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
