"""empty message

Revision ID: ed8d0590e0ef
Revises: 1488a6d6dc5a
Create Date: 2025-07-25 10:46:17.387331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed8d0590e0ef'
down_revision = '1488a6d6dc5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_point', sa.String(length=255), nullable=True))
        batch_op.drop_column('interepoint')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interepoint', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('interest_point')

    op.drop_table('tasks')
    # ### end Alembic commands ###
